steps:
  # Build package using maven
  - name: maven:3.8.5-openjdk-17
    entrypoint: mvn
    args: ['package']

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    script: |
      docker build -t northamerica-northeast1-docker.pkg.dev/ncpl-449223/ncpl-project5/spring-boot-app:latest .
    automapSubstitutions: true

  # Publish image to registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "northamerica-northeast1-docker.pkg.dev/ncpl-449223/ncpl-project5/spring-boot-app:latest"]

  # Deploy container to Kubernetes
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=gke.yaml
      - --location=northamerica-northeast1
      - --cluster=ncpl-cluster-1
  
  # Deploy app to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
    timeout: '1600s'

options:
  logging: CLOUD_LOGGING_ONLY