steps:
  - name: maven:3.8.5-openjdk-17
    entrypoint: mvn
    args: ['package']

  - name: 'gcr.io/cloud-builders/docker'
    script: |
      docker build -t northamerica-northeast2-docker.pkg.dev/ncpl-449223/ncpl-project2:latest .
    automapSubstitutions: true

images:
  - 'northamerica-northeast2-docker.pkg.dev/ncpl-449223/ncpl-project2:latest'